config/routes.rb
Rails.application.routes.draw do
  root to: 'themes#index'
  
  resources :themes do 
  resources :posts, only: [:show,:create, :destroy]
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def show
    @post = Post.find(params[:id])
   end
  
  
  
  def create
    @theme = Theme.find(params[:theme_id])
    @post = Post.new(post_params)
    @post.theme_id = @theme.id
    if @post.save
      
      flash[:success] = 'コメントが投稿されました'
      redirect_back(fallback_location: root_path)
    else
      flash.now[:danger] = 'コメントが投稿されませんでした'
      redirect_back(fallback_location: root_path)
    end
  end


 
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    flash[:success] = 'コメントは削除されました'
    redirect_to themes_url
  end
  
  
  private
  
  def post_params
    params.require(:post).permit( :name, :body)
  end
  
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find(params[:id])
    @posts = @theme.posts
    @post = Post.new
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    
    if @theme.save
      flash[:success] = 'スレッドが作成されました'
      redirect_to @theme
    else
      flash.now[:danger] = 'スレッドが作成されませんでした'
      render :new
    end
    
  end

  def edit
    @theme = Theme.find(params[:id])
  end

  def update
    @theme = Theme.find(params[:id])
    if @theme.update(theme_params)
      flash[:success] = 'スレッドが更新されました'
      redirect_to @theme
    else
      flash.now[:danger] = 'スレッドが更新されませんでした'
      render :edit
    end
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    
    flash[:success] = 'スレッドは削除されました'
    redirect_to themes_url
  end
  
  
  private
  
  def theme_params
    params.require(:theme).permit(:title)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
  def current_theme
    @current_theme = Theme.find_by(id: theme[:theme_id])
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div>
<%= message %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardpost</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      
      <%= render 'layouts/flash_messages' %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/posts/show.html.erb
<h1> <%= @post.name %> : <%= @post.body %></h1>


<%= link_to 'スレッド一覧に戻る', themes_path %>
<%= link_to 'このコメントを削除する', theme_post_path, method: :delete %> 

app/views/themes/edit.html.erb
<h1> 「<%= @theme.title %>」のスレッドの編集</h1>

<%= form_for(@theme) do |f| %>
<%= f.label :title, 'スレッド名'  %>
<%= f.text_field :title %>
<%= f.submit '編集' %>
<% end %>
<%= link_to 'スレッド一覧に戻る',themes_path %>

app/views/themes/index.html.erb
<h1>スレッド一覧</h1>

<ul>
  <% @themes.each do |theme| %>
  <li><%= link_to theme.title, theme %></li>
  <% end %>
</ul>

<%= link_to 'スレッドの作成', new_theme_path %>

app/views/themes/new.html.erb
<h1>スレッド作成</h1>
<%= form_for(@theme) do |f| %>
<%= f.label :title, 'スレッド名'  %>
<%= f.text_field :title %>
<%= f.submit '作成' %>
<% end %>
<%= link_to 'スレッド一覧に戻る',themes_path %>

app/views/themes/show.html.erb
<h1> 「<%= @theme.title %>」のスレッド</h1>

<h2>コメント一覧</h2>

<% @posts.each_with_index  do |post, idx| %>
  <div>
    <%= idx + 1 %>: <%= post.name %>
    <br>
    <%= link_to post.bodygit, theme_post_path(@theme.id,post.id) %>
    <hr>
  </div>
<% end %>

<%= form_for ([@theme, @post]) do |f| %>
  <%= f.label :name, '名前' %>
  <%= f.text_field :name %>
  <%= f.label :body, 'コメント' %>
  <%= f.text_field :body %>
  <%= f.submit '投稿する' %>
<% end %>


<%= link_to 'スレッド一覧に戻る', themes_path %>
<%= link_to 'このスレッドを編集する', edit_theme_path(@theme) %>
<%= link_to 'このスレッドを削除する', @theme, method: :delete %> 